exclude = [
    ".git",
    "__pycache__",
    "*.ipynb",
    "*.ipynb_checkpoints",
]
ignore = ["E501","F401"]
line-length = 100
select = [
    "E",
    "F",
    "W",
]

[per-file-ignores]
"__init__.py" = [
    "F401",
    "F811",
]
