default_status_mapping = {
    1: True,
    0: False,
}
COMORB_CONFIG = [
    {
        "pipe_name": "myocardial_infarction",
        "label_name": "IDM",
        "color": "LightPink",
        "selection_type": "binary",
        "status_mapping": default_status_mapping,
        "excel_index": 1,
        "ecci_weight": 1,
        "ecci_weight_quan": 0,
        "position": 0,
    },
    {
        "pipe_name": "congestive_heart_failure",
        "label_name": "Insuff. Card. Cong.",
        "color": "Crimson",
        "selection_type": "binary",
        "status_mapping": default_status_mapping,
        "excel_index": [2, 19],
        "ecci_weight": 1,
        "ecci_weight_quan": 2,
        "position": 1,
    },
    {
        "pipe_name": "peripheral_vascular_disease",
        "label_name": "Maladies Vasc. Periph.",
        "color": "LightCoral",
        "selection_type": "binary",
        "status_mapping": default_status_mapping,
        "excel_index": [3, 20],
        "ecci_weight_quan": 0,
        "position": 2,
    },
    {
        "pipe_name": "cerebrovascular_accident",
        "label_name": "Maladies Cérébro-Vasc.",
        "color": "LightSalmon",
        "selection_type": "binary",
        "status_mapping": default_status_mapping,
        "excel_index": 4,
        "ecci_weight": 1,
        "ecci_weight_quan": 0,
        "position": 3,
    },
    {
        "pipe_name": "dementia",
        "label_name": "Démence",
        "color": "Gold",
        "selection_type": "binary",
        "status_mapping": default_status_mapping,
        "excel_index": 5,
        "ecci_weight": 1,
        "ecci_weight_quan": 2,
        "position": 4,
    },
    {
        "pipe_name": "COPD",
        "label_name": "Maladies Pulmo. Chron.",
        "color": "PapayaWhip",
        "selection_type": "binary",
        "status_mapping": default_status_mapping,
        "excel_index": 6,
        "ecci_weight": 1,
        "ecci_weight_quan": 1,
        "position": 5,
    },
    {
        "pipe_name": "connective_tissue_disease",
        "label_name": "Maladies des Tissus Conj.",
        "color": "Tan",
        "selection_type": "binary",
        "status_mapping": default_status_mapping,
        "excel_index": 7,
        "ecci_weight": 1,
        "ecci_weight_quan": 1,
        "position": 6,
    },
    {
        "pipe_name": "peptic_ulcer_disease",
        "label_name": "Ulcères gastriques",
        "color": "LimeGreen",
        "selection_type": "binary",
        "status_mapping": default_status_mapping,
        "excel_index": 8,
        "ecci_weight": 1,
        "ecci_weight_quan": 0,
        "position": 7,
    },
    {
        "pipe_name": "CKD",
        "label_name": "Maladies du Rein",
        "color": "DarkOliveGreen",
        "selection_type": "binary",
        "status_mapping": default_status_mapping,
        "excel_index": 9,
        "ecci_weight": 2,
        "ecci_weight_quan": 1,
        "position": 11,
    },
    {
        "pipe_name": "AIDS",
        "label_name": "SIDA",
        "color": "MediumVioletRed",
        "selection_type": "binary",
        "status_mapping": default_status_mapping,
        "excel_index": 10,
        "ecci_weight": 6,
        "ecci_weight_quan": 4,
        "position": 15,
    },
    {
        "pipe_name": "hemiplegia",
        "label_name": "Hémiplégie",
        "color": "DarkKhaki",
        "selection_type": "binary",
        "status_mapping": default_status_mapping,
        "excel_index": 11,
        "ecci_weight": 2,
        "ecci_weight_quan": 2,
        "position": 10,
    },
    {
        "pipe_name": "diabetes",
        "label_name": "Diabète",
        "color": "Turquoise",
        "selection_type": "list",
        "status_mapping": {
            2: "2:Avec atteintes d'organes",
            1: "1:Sans atteintes d'organes",
            0: "0:Absence",
        },
        "selection_values": [
            "2:Avec atteintes d'organes",
            "1:Sans atteintes d'organes",
            "0:Absence",
        ],
        "default_value": "1:Sans atteintes d'organes",
        "excel_index": 12,
        "ecci_weight": [1, 2],
        "ecci_weight_quan": [0, 1],
        "position": 9,
    },
    {
        "pipe_name": "liver_disease",
        "label_name": "Maladies du Foie",
        "color": "SeaGreen",
        "selection_type": "list",
        "status_mapping": {
            2: "2:Modérée/Sévère",
            1: "1:Faible",
            0: "0:Absence",
        },
        "selection_values": [
            "2:Modérée/Sévère",
            "1:Faible",
            "0:Absence",
        ],
        "default_value": "1:Faible",
        "excel_index": 13,
        "ecci_weight": [1, 3],
        "ecci_weight_quan": [2, 4],
        "position": 8,
    },
    {
        "pipe_name": "solid_tumor",
        "label_name": "Cancer",
        "color": "PowderBlue",
        "selection_type": "list",
        "status_mapping": {
            2: "2:Métastasé",
            1: "1:Solide",
            0: "0:Absence",
        },
        "selection_values": [
            "2:Métastasé",
            "1:Solide",
            "0:Absence",
        ],
        "default_value": "1:Solide",
        "excel_index": 14,
        "ecci_weight": [2, 6],
        "ecci_weight_quan": [2, 6],
        "family": "Cancer",
        "position": 12,
    },
    {
        "pipe_name": "leukemia",
        "label_name": "Leucemie",
        "color": "SkyBlue",
        "selection_type": "binary",
        "status_mapping": default_status_mapping,
        "excel_index": 15,
        "ecci_weight": 2,
        "ecci_weight_quan": 2,
        "family": "Cancer",
        "position": 13,
    },
    {
        "pipe_name": "lymphoma",
        "label_name": "Lymphome",
        "color": "PaleTurquoise",
        "selection_type": "binary",
        "status_mapping": default_status_mapping,
        "excel_index": 16,
        "ecci_weight": 2,
        "ecci_weight_quan": 2,
        "family": "Cancer",
        "position": 14,
    },
    {
        "pipe_name": "alcohol",
        "label_name": "Alcool",
        "color": "Plum",
        "selection_type": "list",
        "status_mapping": {
            2: "2:Sevré",
            1: "1:Présent",
            0: "0:Absence",
        },
        "selection_values": [
            "2:Sevré",
            "1:Présent",
            "0:Absence",
        ],
        "default_value": "1:Présent",
        "excel_index": 17,
        "ecci_weight": [0, 0],
        "ecci_weight_quan": [0, 0],
        "position": 16,
    },
    {
        "pipe_name": "tobacco",
        "label_name": "Tabagisme",
        "color": "Orange",
        "selection_type": "list",
        "status_mapping": {
            2: "2:Sevré",
            1: "1:Présent",
            0: "0:Absence",
        },
        "selection_values": [
            "2:Sevré",
            "1:Présent",
            "0:Absence",
        ],
        "default_value": "1:Présent",
        "excel_index": 18,
        "ecci_weight": [0, 0],
        "ecci_weight_quan": [0, 0],
        "position": 17,
    },
    # {
    #     "pipe_name": "adrenal_insufficiency",
    #     "label_name": "Insuff. Surrénale",
    #     "color": "PaleTurquoise",
    #     "selection_type": "binary",
    #     "status_mapping": default_status_mapping,
    #     "excel_index": 22,
    # },
    # {
    #     "pipe_name": "atrial_fibrillation",
    #     "label_name": "FA",
    #     "color": "PaleTurquoise",
    #     "selection_type": "binary",
    #     "status_mapping": default_status_mapping,
    #     "excel_index": 19,
    # },
    # {
    #     "pipe_name": "myasthenia",
    #     "label_name": "Myasthénie",
    #     "color": "PaleTurquoise",
    #     "selection_type": "binary",
    #     "status_mapping": default_status_mapping,
    #     "excel_index": 21,
    # },
    # {
    #     "pipe_name": "hypertension",
    #     "label_name": "HTA",
    #     "color": "PaleTurquoise",
    #     "selection_type": "binary",
    #     "status_mapping": default_status_mapping,
    #     "excel_index": 20,
    # },
]
